* Add -g|--group and -u|--user handling to rebuildfstab-uuid.

diff --git a/rebuildfstab-uuid b/rebuildfstab-uuid
--- a/rebuildfstab-uuid
+++ b/rebuildfstab-uuid
@@ -51,6 +51,8 @@ usage()
 	echo "-h|--help print this help"
 	echo "-w|--write-fstab (re)create the fstab file"
 	echo "-m|--make-mountpoints  (re)create mountpoints in /media"
+	echo "-g|--group group to create special mount options for"
+	echo "-u|--user user to create special mount options for"
 }
 #--------------------------------------------------------------
 
@@ -300,7 +302,7 @@ floppy_devs()
 # preparation
 #--------------------------------------------------------------
 
-TEMP=`getopt -o hmw --long help,make-mountpoints,write-fstab \
+TEMP=`getopt -o hmwg:u: --long help,make-mountpoints,write-fstab,group:,user: \
      -n  "$(basename $0)" -- "$@"`
 
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
@@ -316,13 +318,27 @@ while true ; do
 			;;
 		-w|--write-fstab) 
 			write_fstab="yes";
-			shift ;;
+			shift
+			;;
 		-m|--make-mountpoints)
 			create_mount_points="yes" ;
-			shift ;;
-
-		--) shift ; break ;;
-		*) echo "Internal error!" ; exit 1 ;;
+			shift
+			;;
+		-g|--group)
+			group="$2"
+			shift 2
+			;;
+		-u|--user)
+			user="$2"
+			shift 2
+			;;
+		--) 
+			shift
+			break ;;
+		*)
+			echo "Internal error!"
+			exit 1
+			;;
 	esac
 done
 
